spring:
  application:
    name: HelloServer2

server:
  port: 7311

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
